name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.5.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # Runs a single command using the runners shell
      - name: Micropython cross
        run: make -C micropython/mpy-cross

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          . $IDF_PATH/export.sh
          cd micropython/ports/esp32
          make BOARD=SEEED_XIAO_ESP32S3 submodules
          make BOARD=SEEED_XIAO_ESP32S3 USER_C_MODULES=../../../../Inkplate-micropython/firmware/usermods/inkplate
